- lambda/main.js
- package-lock.json
- package.json
Added new function declaration for defining image types, and placeholder for converting said images to next gen formats.
> Next-Gen Image Formats

- Dockerfile
- install.sh
This is an "untested" dockerization of the imagemagick binary dependencies. It also includes a WIP shell script for launching the dockerization as well as actually copying over the build dependencies to the local file system. Note: might be more "JavaScript-y" if I convert the bash script into a pure JS file/function.
> Feature - Dockerization of the lambda dependencies

- install.sh
- lambda/magick.js
- lambda/package.json
- lambda/vehicles/local.js
- lambda/vehicles/s3.js
This fixes a bug where the lambda code was looking for the tmp directory inside the function execution directory.
> Bugfix - Local and remote tmp paths are different.

- Dockerfile
Install libpng and libwebp from packages repository
Issue: #29
> Fix PNG and WebP image encoding formats

- lambda/magick.js
- lambda/main.js
- lambda/publishMessage.js
- lambda/vehicles/s3.js
This is the initial setup of SNS messages, which decorates the JSON file with the generated response from the magine service. Still needs to be tested heavily, since it was written without any feedback loop at all.
> Initial setup of SNS data flow

- lambda/options/jpg_conversion.json
> Added a new file to handle the naming conventions

- .circleci/config.yml
- terraform/environments/qa/main.tf
- terraform/environments/qa/versions.tf
- terraform/modules/magine/main.tf
This sets up a qa environment and pipeline for Magine.
It also includes a permissions fix allowing actions to be performed on objects belonging to the bucket that are required for uploads.
> Feature - QA Environment

- lambda/vehicles/s3.js
> Bugfix - No content type was being sent to s3

- README.md
Updating with some user documentation
> Updating README with some S3 instructions

- lambda/options/product-list_rules.json
- lambda/options/social_rules.json
This is related to the work being done in https://github.com/MaisonetteWorld/maisonette-cms/pull/382.
> Added new rule for resizing, modified the ratio of the other

- lambda/options/box_rules.json
- lambda/options/circle_rules.json
- lambda/options/hero_rules.json
This changes the defaults to be larger in certain cases, while being smaller in others. Its very much based on my own implementation rules, realizing that I need to make this more of a plugin-based system.
> Feature - Resize certain images more appropriately based on screen size

- lambda/vehicles/s3.js
- terraform/modules/magine/main.tf
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property
> [TEC-607] Updated to have max age

- .circleci/config.yml
Also moved ppd into the main workflow
> Allow develop and release* branches to deploy to stg and ppd, and master to prd

- lambda/magick.js
- lambda/package.json
Uses https://imagemagick.org/script/identify.php instead of `image-size`.
> [TEC-2789] Use magick identify instead of image-size

- lambda/package.json
- [TEC-2619] Save image dimensions in image object @dinohamzic
- [TEC-2795] 403 on images @dinohamzic @KempfCreative 
- [TEC-2789] Use magick identify instead of image-size @dinohamzic 
- [TEC-2567] Gif optimization @dinohamzic 
[TEC-2619]: https://maisonette.atlassian.net/browse/TEC-2619
[TEC-2795]: https://maisonette.atlassian.net/browse/TEC-2795
[TEC-2789]: https://maisonette.atlassian.net/browse/TEC-2789
> [Develop] Release 2.2.0

- lambda/package.json
- [TEC-2567] Gif optimization 2 @dinohamzic 
> [Master] Release 2.2.1

- lambda/package.json
- [TEC-2567] Gif optimization 2 @dinohamzic 
> [Develop] Release 2.2.1

- lambda/package.json
- lambda/resize.js
- [TEC-2567] Gif optimization 3 @dinohamzic 
> [Master] Release 2.2.2

- lambda/package.json
- [TEC-2567] Gif optimization 3 @dinohamzic 
> [Develop] Release 2.2.2

- lambda/magick.js
Not ideal, but it should return the original image if there was one.
> TEC-2993 Bugfix for when images don't optimize to use the original.

- lambda/package.json
**Changes:**
- [TEC-2993](https://maisonette.atlassian.net/browse/TEC-2993) - Bugfix for when images don't optimize to use the original @KempfCreative
> [Master] Release 2.2.3

- lambda/package.json
**Changes:**
- [TEC-2993](https://maisonette.atlassian.net/browse/TEC-2993) - Bugfix for when images don't optimize to use the original @KempfCreative
> [Develop] Release 2.2.3

- Dockerfile
- lambda/format.js
- lambda/magick.js
- lambda/package.json
- lambda/resize.js
**Bug Fixes:**
- [TEC-2991](https://maisonette.atlassian.net/browse/TEC-2991) - Specific image not uploading in CMS @danfyfe 
- [TEC-3036](https://maisonette.atlassian.net/browse/TEC-3036) - Switch to Progressive JPEG - CMS powered images @danfyfe
> [Master] - Release 2.2.4
